name: Cleanup Old Artifacts
description: Delete old workflow artifacts

inputs:
  age:
    description: 'Age of artifacts to delete (e.g., 7 days)'
    required: false
    default: '7 days'
  skip-recent:
    description: 'Number of recent artifacts to skip'
    required: false
    default: '3'
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: composite
  steps:
    - name: Delete old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: ${{ inputs.age }}
        skip-recent: ${{ inputs.skip-recent }}
        token: ${{ inputs.github-token }}
