name: Setup Infisical Secrets
description: Fetch secrets from Infisical vault

inputs:
  project-slug:
    description: 'Infisical project slug'
    required: false
    default: 'kubernetes'
  env-slug:
    description: 'Infisical environment slug'
    required: false
    default: 'prod'
  domain:
    description: 'Infisical domain URL'
    required: false
    default: 'https://vault.armandleopold.fr'
  infisical-client-id:
    description: 'Infisical Client ID'
    required: true
  infisical-client-secret:
    description: 'Infisical Client Secret'
    required: true

runs:
  using: composite
  steps:
    - name: Fetch secrets from Infisical
      uses: Infisical/secrets-action@v1.0.16
      with:
        method: universal
        client-id: ${{ inputs.infisical-client-id }}
        client-secret: ${{ inputs.infisical-client-secret }}
        project-slug: ${{ inputs.project-slug }}
        env-slug: ${{ inputs.env-slug }}
        secret-path: /
        export-type: env
        domain: ${{ inputs.domain }}
