version: "3"
services:
  frontend:
    image: qalita.azurecr.io/qalita/frontend:2.1.0
    container_name: frontend
    environment:
      - QALITA_API_URL=http://backend:3080
    ports:
      - "3002:3000"
    depends_on:
      - backend
  backend:
    image: qalita.azurecr.io/qalita/backend:2.1.0
    container_name: backend
    ports:
      - "3080:3080"
    tty: true
    environment:
      - POSTGRESQL_PASSWORD=*****************
      - POSTGRESQL_USERNAME=qalita
      - POSTGRESQL_SERVER=db
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=qalitadb
      - REDIS_SERVER=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - QALITA_INIT_SLEEP=3
      - QALITA_ADMIN_USERNAME=admin
      - QALITA_ADMIN_PASSWORD=*****************
      - QALITA_SECRET_KEY=*****************
      - QALITA_ALGORITHM=HS256
      - QALITA_ACCESS_TOKEN_EXPIRE_MINUTES=240
      - QALITA_ENV=PROD
      - QALITA_API_PORT=3080
      - QALITA_API_HOST=0.0.0.0
      - QALITA_FRONTEND_URL=http://localhost:3000
      - QALITA_ORGANIZATION_NAME=Qalita Localhost
      - QALITA_API_WORKER=4
      - QALITA_S3_URL=http://s3:8333
      - QALITA_S3_KEY_ID=*****************
      - QALITA_S3_KEY_SECRET=*****************
    depends_on:
      - db
      - cache
      - s3
  db:
    image: qalita.azurecr.io/postgresql:15.4.0
    tty: true
    ports:
      - "5432:5432"
    container_name: db
    environment:
      - POSTGRESQL_PASSWORD=*****************
      - POSTGRESQL_USERNAME=qalita
      - POSTGRESQL_DATABASE=qalitadb
      - POSTGRESQL_PORT=5432
    volumes:
      - data:/bitnami/postgresql
  cache:
    image: qalita.azurecr.io/redis:7.4.2
    hostname: redis-cache
    container_name: cache
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - cache:/data
  s3:
    image: qalita.azurecr.io/seaweedfs:3.80
    container_name: s3
    ports:
      - "8333:8333"
      - "8080:8080"
      - "9333:9333"
    volumes:
      - datas3:/data
      - ./s3_config.json:/s3_config.json
    command: server -dir=/data -s3 -s3.port 8333 -s3.config "/s3_config.json"
volumes:
  data:
  cache:
  datas3:
