name: qalita-platform-frontend-stack
services:
  backend:
    image: qalita.azurecr.io/qalita/backend:latest
    ports:
      - "3080:3080"
    environment:
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_USERNAME=qalita
      - POSTGRESQL_SERVER=db
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=qalitadb
      - REDIS_SERVER=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - MAIL_USERNAME=test
      - MAIL_PASSWORD=test
      - MAIL_FROM=no-reply@example.com
      - MAIL_PORT=1025
      - MAIL_SERVER=mailpit
      - MAIL_STARTTLS=False
      - MAIL_SSL_TLS=False
      - MAIL_FROM_NAME="Dev Server"
      - QALITA_INIT_SLEEP=3
      - QALITA_ADMIN_USERNAME=admin
      - QALITA_ADMIN_PASSWORD=password
      - QALITA_SECRET_KEY=************
      - QALITA_LICENSE_USER=
      - QALITA_LICENSE_KEY=
      - QALITA_ALGORITHM=HS256
      - QALITA_ACCESS_TOKEN_EXPIRE_MINUTES=240
      - QALITA_ENV=DEMO
      - QALITA_API_PORT=3080
      - QALITA_API_HOST=0.0.0.0
      - QALITA_ORGANIZATION_NAME=Qalita Demo Localhost
      - QALITA_API_WORKER=4
      - QALITA_AUTH_MODE=table
      - QALITA_S3_URL=http://s3:8333
      - QALITA_S3_KEY_ID=******************
      - QALITA_S3_KEY_SECRET=***********************
      - QALITA_PUBLIC_PLATFORM_URL=http://localhost:3012
      - QALITA_PUBLIC_DOC_URL=http://localhost:3011
      - QALITA_PUBLIC_API_URL=http://localhost:3080
    depends_on:
      - db
      - cache
      - s3
      - mailpit
  doc:
    image: qalita.azurecr.io/qalita/doc:latest
    ports:
      - 3011:3000
    environment:
      - QALITA_API_URL=http://localhost:3080
    user: node
  frontendprod:
    image: qalita.azurecr.io/qalita/frontend:latest
    environment:
      - QALITA_API_URL=http://backend:3080
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_WEBPACK_USEPOLLING=false
      - NEXT_SHARP_PATH=/app/node_modules/sharp
      - NODE_ENV=production
    ports:
      - "3012:3000"
    depends_on:
      - backend
      - doc
  db:
    image: qalita.azurecr.io/postgresql:15.4.0
    tty: true
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_USERNAME=qalita
      - POSTGRESQL_DATABASE=qalitadb
      - POSTGRESQL_PORT=5432
    volumes:
      - data:/bitnami/postgresql
  cache:
    image: qalita.azurecr.io/redis:7.4.2
    hostname: cache
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  mailpit:
    image: qalita.azurecr.io/mailpit:v1.22.2
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  s3:
    image: qalita.azurecr.io/seaweedfs:3.80
    ports:
      - "8333:8333"
      - "8080:8080"
      - "9333:9333"
    volumes:
      - datas3:/data
      - ./s3_config.json:/s3_config.json
    command: server -dir=/data -s3 -s3.port 8333 -s3.config "/s3_config.json"
volumes:
  data:
  datas3:
